package com.magalu.logistica.app.agendamento.api.domain;
// Generated 20 de jun de 2021 16:08:19 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agendamento generated by hbm2java
 */
@Entity
@Table(name = "agendamento", catalog = "logistica")
public class Agendamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idAgendamento;
	private String mensagem;
	private Date dataHoraCriacao;
	private Date dataHoraParaEnvio;
	private Set<DestinatarioComunicacao> destinatarioComunicacaos = new HashSet<>(0);

	public Agendamento() {
	}

	public Agendamento(String mensagem, Date dataHoraCriacao, Date dataHoraParaEnvio) {
		this.mensagem = mensagem;
		this.dataHoraCriacao = dataHoraCriacao;
		this.dataHoraParaEnvio = dataHoraParaEnvio;
	}

	public Agendamento(String mensagem, Date dataHoraCriacao, Date dataHoraParaEnvio,
			Set<DestinatarioComunicacao> destinatarioComunicacaos) {
		this.mensagem = mensagem;
		this.dataHoraCriacao = dataHoraCriacao;
		this.dataHoraParaEnvio = dataHoraParaEnvio;
		this.destinatarioComunicacaos = destinatarioComunicacaos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_agendamento", unique = true, nullable = false)
	public Integer getIdAgendamento() {
		return this.idAgendamento;
	}

	public void setIdAgendamento(Integer idAgendamento) {
		this.idAgendamento = idAgendamento;
	}

	@Column(name = "mensagem", nullable = false, length = 300)
	public String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_criacao", nullable = false, length = 19)
	public Date getDataHoraCriacao() {
		return this.dataHoraCriacao;
	}

	public void setDataHoraCriacao(Date dataHoraCriacao) {
		this.dataHoraCriacao = dataHoraCriacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_para_envio", nullable = false, length = 19)
	public Date getDataHoraParaEnvio() {
		return this.dataHoraParaEnvio;
	}

	public void setDataHoraParaEnvio(Date dataHoraParaEnvio) {
		this.dataHoraParaEnvio = dataHoraParaEnvio;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "agendamento")
	public Set<DestinatarioComunicacao> getDestinatarioComunicacaos() {
		return this.destinatarioComunicacaos;
	}

	public void setDestinatarioComunicacaos(Set<DestinatarioComunicacao> destinatarioComunicacaos) {
		this.destinatarioComunicacaos = destinatarioComunicacaos;
	}

}