package com.magalu.logistica.app.agendamento.api.domain;
// Generated 20 de jun de 2021 16:08:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CanalComunicacao generated by hbm2java
 */
@Entity
@Table(name = "canal_comunicacao", catalog = "logistica")
public class CanalComunicacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCanalComunicacao;
	private String descricaoCanalComunicacao;

	public CanalComunicacao() {
	}

	public CanalComunicacao(int idCanalComunicacao, String descricaoCanalComunicacao) {
		this.idCanalComunicacao = idCanalComunicacao;
		this.descricaoCanalComunicacao = descricaoCanalComunicacao;
	}

	@Id

	@Column(name = "id_canal_comunicacao", unique = true, nullable = false)
	public int getIdCanalComunicacao() {
		return this.idCanalComunicacao;
	}

	public void setIdCanalComunicacao(int idCanalComunicacao) {
		this.idCanalComunicacao = idCanalComunicacao;
	}

	@Column(name = "descricao_canal_comunicacao", nullable = false, length = 60)
	public String getDescricaoCanalComunicacao() {
		return this.descricaoCanalComunicacao;
	}

	public void setDescricaoCanalComunicacao(String descricaoCanalComunicacao) {
		this.descricaoCanalComunicacao = descricaoCanalComunicacao;
	}

}
