package com.magalu.logistica.app.agendamento.api.domain;
// Generated 20 de jun de 2021 16:08:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DestinatarioComunicacaoId generated by hbm2java
 */
@Embeddable
public class DestinatarioComunicacaoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAgendamento;
	private int idPessoaDestinatario;
	private int idCanalComunicacao;

	public DestinatarioComunicacaoId() {
	}

	public DestinatarioComunicacaoId(int idAgendamento, int idPessoaDestinatario, int idCanalComunicacao) {
		this.idAgendamento = idAgendamento;
		this.idPessoaDestinatario = idPessoaDestinatario;
		this.idCanalComunicacao = idCanalComunicacao;
	}

	@Column(name = "id_agendamento", nullable = false)
	public int getIdAgendamento() {
		return this.idAgendamento;
	}

	public void setIdAgendamento(int idAgendamento) {
		this.idAgendamento = idAgendamento;
	}

	@Column(name = "id_pessoa_destinatario", nullable = false)
	public int getIdPessoaDestinatario() {
		return this.idPessoaDestinatario;
	}

	public void setIdPessoaDestinatario(int idPessoaDestinatario) {
		this.idPessoaDestinatario = idPessoaDestinatario;
	}

	@Column(name = "id_canal_comunicacao", nullable = false)
	public int getIdCanalComunicacao() {
		return this.idCanalComunicacao;
	}

	public void setIdCanalComunicacao(int idCanalComunicacao) {
		this.idCanalComunicacao = idCanalComunicacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DestinatarioComunicacaoId))
			return false;
		DestinatarioComunicacaoId castOther = (DestinatarioComunicacaoId) other;

		return (this.getIdAgendamento() == castOther.getIdAgendamento())
				&& (this.getIdPessoaDestinatario() == castOther.getIdPessoaDestinatario())
				&& (this.getIdCanalComunicacao() == castOther.getIdCanalComunicacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAgendamento();
		result = 37 * result + this.getIdPessoaDestinatario();
		result = 37 * result + this.getIdCanalComunicacao();
		return result;
	}

}
