package com.magalu.logistica.app.agendamento.api.domain;
// Generated 20 de jun de 2021 16:08:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DestinatarioComunicacao generated by hbm2java
 */
@Entity
@Table(name = "destinatario_comunicacao", catalog = "logistica")
public class DestinatarioComunicacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DestinatarioComunicacaoId id;
	private Agendamento agendamento;
	private PessoaCanalComunicacao pessoaCanalComunicacaoByIdCanalComunicacao;
	private PessoaCanalComunicacao pessoaCanalComunicacaoByIdPessoaDestinatario;
	private StatusComunicacao statusComunicacao;

	public DestinatarioComunicacao() {
	}

	public DestinatarioComunicacao(DestinatarioComunicacaoId id, Agendamento agendamento,
			PessoaCanalComunicacao pessoaCanalComunicacaoByIdCanalComunicacao,
			PessoaCanalComunicacao pessoaCanalComunicacaoByIdPessoaDestinatario, StatusComunicacao statusComunicacao) {
		this.id = id;
		this.agendamento = agendamento;
		this.pessoaCanalComunicacaoByIdCanalComunicacao = pessoaCanalComunicacaoByIdCanalComunicacao;
		this.pessoaCanalComunicacaoByIdPessoaDestinatario = pessoaCanalComunicacaoByIdPessoaDestinatario;
		this.statusComunicacao = statusComunicacao;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAgendamento", column = @Column(name = "id_agendamento", nullable = false)),
			@AttributeOverride(name = "idPessoaDestinatario", column = @Column(name = "id_pessoa_destinatario", nullable = false)),
			@AttributeOverride(name = "idCanalComunicacao", column = @Column(name = "id_canal_comunicacao", nullable = false)) })
	public DestinatarioComunicacaoId getId() {
		return this.id;
	}

	public void setId(DestinatarioComunicacaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agendamento", nullable = false, insertable = false, updatable = false)
	public Agendamento getAgendamento() {
		return this.agendamento;
	}

	public void setAgendamento(Agendamento agendamento) {
		this.agendamento = agendamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_canal_comunicacao", nullable = false, insertable = false, updatable = false)
	public PessoaCanalComunicacao getPessoaCanalComunicacaoByIdCanalComunicacao() {
		return this.pessoaCanalComunicacaoByIdCanalComunicacao;
	}

	public void setPessoaCanalComunicacaoByIdCanalComunicacao(
			PessoaCanalComunicacao pessoaCanalComunicacaoByIdCanalComunicacao) {
		this.pessoaCanalComunicacaoByIdCanalComunicacao = pessoaCanalComunicacaoByIdCanalComunicacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pessoa_destinatario", nullable = false, insertable = false, updatable = false)
	public PessoaCanalComunicacao getPessoaCanalComunicacaoByIdPessoaDestinatario() {
		return this.pessoaCanalComunicacaoByIdPessoaDestinatario;
	}

	public void setPessoaCanalComunicacaoByIdPessoaDestinatario(
			PessoaCanalComunicacao pessoaCanalComunicacaoByIdPessoaDestinatario) {
		this.pessoaCanalComunicacaoByIdPessoaDestinatario = pessoaCanalComunicacaoByIdPessoaDestinatario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_status_comunicacao", nullable = false)
	public StatusComunicacao getStatusComunicacao() {
		return this.statusComunicacao;
	}

	public void setStatusComunicacao(StatusComunicacao statusComunicacao) {
		this.statusComunicacao = statusComunicacao;
	}

}
