package com.magalu.logistica.app.agendamento.api.domain;
// Generated 20 de jun de 2021 16:08:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa", catalog = "logistica")
public class Pessoa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPessoa;
	private String nomePessoa;

	public Pessoa() {
	}

	public Pessoa(String nomePessoa) {
		this.nomePessoa = nomePessoa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_pessoa", unique = true, nullable = false)
	public Integer getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(Integer idPessoa) {
		this.idPessoa = idPessoa;
	}

	@Column(name = "nome_pessoa", nullable = false, length = 100)
	public String getNomePessoa() {
		return this.nomePessoa;
	}

	public void setNomePessoa(String nomePessoa) {
		this.nomePessoa = nomePessoa;
	}

}
