package com.magalu.logistica.app.agendamento.api.domain;
// Generated 20 de jun de 2021 16:08:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PessoaCanalComunicacaoId generated by hbm2java
 */
@Embeddable
public class PessoaCanalComunicacaoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCanalComunicacao;
	private int idPessoa;

	public PessoaCanalComunicacaoId() {
	}

	public PessoaCanalComunicacaoId(int idCanalComunicacao, int idPessoa) {
		this.idCanalComunicacao = idCanalComunicacao;
		this.idPessoa = idPessoa;
	}

	@Column(name = "id_canal_comunicacao", nullable = false)
	public int getIdCanalComunicacao() {
		return this.idCanalComunicacao;
	}

	public void setIdCanalComunicacao(int idCanalComunicacao) {
		this.idCanalComunicacao = idCanalComunicacao;
	}

	@Column(name = "id_pessoa", nullable = false)
	public int getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PessoaCanalComunicacaoId))
			return false;
		PessoaCanalComunicacaoId castOther = (PessoaCanalComunicacaoId) other;

		return (this.getIdCanalComunicacao() == castOther.getIdCanalComunicacao())
				&& (this.getIdPessoa() == castOther.getIdPessoa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCanalComunicacao();
		result = 37 * result + this.getIdPessoa();
		return result;
	}

}
