package com.magalu.logistica.app.agendamento.api.domain;
// Generated 20 de jun de 2021 16:08:19 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PessoaCanalComunicacao generated by hbm2java
 */
@Entity
@Table(name = "pessoa_canal_comunicacao", catalog = "logistica")
public class PessoaCanalComunicacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PessoaCanalComunicacaoId id;
	private Set<DestinatarioComunicacao> destinatarioComunicacaos= new HashSet<>(0);

	public PessoaCanalComunicacao() {
	}

	public PessoaCanalComunicacao(PessoaCanalComunicacaoId id) {
		this.id = id;
	}

	public PessoaCanalComunicacao(PessoaCanalComunicacaoId id,
			Set<DestinatarioComunicacao> destinatarioComunicacaos) {
		this.id = id;
		this.destinatarioComunicacaos = destinatarioComunicacaos;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCanalComunicacao", column = @Column(name = "id_canal_comunicacao", nullable = false)),
			@AttributeOverride(name = "idPessoa", column = @Column(name = "id_pessoa", nullable = false)) })
	public PessoaCanalComunicacaoId getId() {
		return this.id;
	}

	public void setId(PessoaCanalComunicacaoId id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoaCanalComunicacao")
	public Set<DestinatarioComunicacao> getDestinatarioComunicacaos() {
		return destinatarioComunicacaos;
	}

	public void setDestinatarioComunicacaos(Set<DestinatarioComunicacao> destinatarioComunicacaos) {
		this.destinatarioComunicacaos = destinatarioComunicacaos;
	}
}

