package com.magalu.logistica.app.agendamento.api.domain;
// Generated 20 de jun de 2021 16:08:19 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatusComunicacao generated by hbm2java
 */
@Entity
@Table(name = "status_comunicacao", catalog = "logistica")
public class StatusComunicacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idStatusComunicacao;
	private String descricaoStatusAgendamento;
	private Set<DestinatarioComunicacao> destinatarioComunicacaos = new HashSet<>(0);

	public StatusComunicacao() {
	}

	public StatusComunicacao(int idStatusComunicacao, String descricaoStatusAgendamento) {
		this.idStatusComunicacao = idStatusComunicacao;
		this.descricaoStatusAgendamento = descricaoStatusAgendamento;
	}

	public StatusComunicacao(int idStatusComunicacao, String descricaoStatusAgendamento,
			Set<DestinatarioComunicacao> destinatarioComunicacaos) {
		this.idStatusComunicacao = idStatusComunicacao;
		this.descricaoStatusAgendamento = descricaoStatusAgendamento;
		this.destinatarioComunicacaos = destinatarioComunicacaos;
	}

	@Id

	@Column(name = "id_status_comunicacao", unique = true, nullable = false)
	public int getIdStatusComunicacao() {
		return this.idStatusComunicacao;
	}

	public void setIdStatusComunicacao(int idStatusComunicacao) {
		this.idStatusComunicacao = idStatusComunicacao;
	}

	@Column(name = "descricao_status_agendamento", nullable = false, length = 45)
	public String getDescricaoStatusAgendamento() {
		return this.descricaoStatusAgendamento;
	}

	public void setDescricaoStatusAgendamento(String descricaoStatusAgendamento) {
		this.descricaoStatusAgendamento = descricaoStatusAgendamento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusComunicacao")
	public Set<DestinatarioComunicacao> getDestinatarioComunicacaos() {
		return this.destinatarioComunicacaos;
	}

	public void setDestinatarioComunicacaos(Set<DestinatarioComunicacao> destinatarioComunicacaos) {
		this.destinatarioComunicacaos = destinatarioComunicacaos;
	}

}
